# .github/workflows/course.yml
name: CS596 Course Build

run-name: ${{ github.actor }} publishing CS596 course

on: [push]

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  pages: write
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event"
      - run: echo "Job now running on a ${{ runner.os }} server"
      - run: echo "Repo ${{ github.repository }} Branch ${{ github.ref }}"
      - name: Check out repository
        uses: actions/checkout@v4
      - run: echo " ${{ github.repository }} repository cloned to runner"
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: mkdir -p output
      - name: Running python
        run: |
          python3 schedgen.py > output/schedule.html
          cp main.css > output
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload static files
        id: deployment
        uses: actions/deploy-pages@v4
      - run: echo "Job's final status is ${{ job.status }}."
    
